@baseUrl=http://localhost:4000

###

# @name root
# Ruta para acceder a la raíz de la API
GET {{baseUrl}}/

###

# @name humans
# Ruta para acceder al archivo humans.txt
GET {{baseUrl}}/humans.txt

### 

# @name registerUser
# Ruta para registrar un nuevo usuario
POST {{baseUrl}}/register 
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password" 
}

### 

# @name loginUser
# Ruta para iniciar sesión
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password" 
}