@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI0ODg2NjQwLCJleHAiOjE3MjQ4ODg0NDB9.iGkc3J2TMoubX-dUotPpqyLquDx0FUKKTLdoEh_nwZc

###

# @name root
# Ruta para acceder a la raíz de la API
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###

# @name humans
# Ruta para acceder al archivo humans.txt
GET {{baseUrl}}/humans.txt

### 

# @name registerUser
# Ruta para registrar un nuevo usuario
POST {{baseUrl}}/register 
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password" 
}

### 

# @name loginUser
# Ruta para iniciar sesión
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password" 
}