@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI0OTA0NDUxLCJleHAiOjE3MjQ5MDYyNTF9.4tk5U-gCBU1dCcCNk_FQTKWOm4B5sI3M8IWYS5Q7Be4

###

# @name root
# Ruta para acceder a la raíz de la API
GET {{baseUrl}}/
Origin: {{baseUrl}}
Authorization: Bearer {{token}}

###

# @name humans
# Ruta para acceder al archivo humans.txt
GET {{baseUrl}}/humans.txt
Origin: {{baseUrl}}

### 

# @name registerUser
# Ruta para registrar un nuevo usuario
POST {{baseUrl}}/register 
Origin: {{baseUrl}}
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password" 
}

### 

# @name loginUser
# Ruta para iniciar sesión
POST {{baseUrl}}/login
Origin: {{baseUrl}}
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password" 
}